name: Deploy to Github Pages

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Deploy with gh-pages
        run: |
          git config --global user.email "axeman.ofic@gmail.com"
          git config --global user.name "Roman Sotnikov"
          npm i
          npm run build
          npm run deploy
